name: Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
      appium:
        image: appium/appium
        ports:
          - 4723:4723
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    
    - name: Run API tests
      run: |
        pytest tests/api/ -v --junitxml=test-results/api-test-results.xml
    
    - name: Run UI tests
      run: |
        pytest tests/ui/ -v --junitxml=test-results/ui-test-results.xml
    
    - name: Run Mobile tests
      run: |
        pytest tests/mobile/ -v --junitxml=test-results/mobile-test-results.xml
    
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results/ 